### ISSUE TITLE
Update Lift properties?

### ISSUE THREAD

**Issue by baviera08** [osrf/romi-js-core-interfaces#4]
@Yadunund correct me if I'm wrong, since we update this message https://github.com/osrf/traffic_editor/blob/master/building_map_msgs/msg/Lift.msg

We should update the Lift properties definitions too, right? to something like this:

``` typescript
export declare class Lift {
    name: string;
    levels: string[];
    doors: Door[];
    wall_graph: Graph;
    ref_x: number;
    ref_y: number;
    ref_yaw: number;
    // new
    width:number;
    depth:number;
    //
    static readonly typeName = "building_map_msgs/msg/Lift";
    static fromObject(obj: any): Lift;
    constructor(name: string, levels: string[], doors: Door[], wall_graph: Graph, ref_x: number, ref_y: number, ref_yaw: number, // new width: number, depth: number);
}
```

And later build and release a new version of an npm package.

**Comment by koonpeng** [comment]
Yea, the lift definitions need to be updated. Unfortunately we don't have a CI solution to keep things synchronized yet. I could make it generate the definitions as a post install step, but that brings in dependency on rmf, python, ros2, typescript among others. What do you think is a better approach? Generating the definitions at install time or publishing the generated definitions and keep things in sync manually or with the help from CI?

**Comment by baviera08** [comment]
Hey @koonpeng I don't know if I'm understanding well your proposal, I need more context to give a proper answer. Could you please help me by answering the following questions and statements?

If I understand the first option well, when the npm package is being installed, you can generate the updated definitions with a post-install step without having to keep the versioned definitions in the repository. But for that, you have to bring many dependencies like Typescript, Ros2, etc.

If the dependencies you add do for npm are only for the people who maintain and update the npm package then I find it to be a reasonable price to pay. If the end-user or system consuming the package doesn't need to install all those dependencies then it is probably worth doing for npm.

But if that is not the case it seems to me that it would be better to publish the generated definitions and keep them versioned in the repository. First, we could do it manually with scripts and then with the help of a CI, depending on the time we have available to do it.

* As a post-install step of this project right? If I'm understanding right this is the idea, right?

* **Current situation:** we have no CI, and we have to install and build the project manually and push manually the updated definitions. That's how we are currently dealing with each update right?
* **About the post-install step:** The post-install step would be a hook, right? 
* If I'm assuming things right, and if we want a CI for this project we will need a webhook that triggers the CI every time `rmf_core` and `traffic_editor` projects have updates. 

If we go with the second option, I think process automation will always be preferred, especially with a project dependent on other projects like this. Here go some thoughts, 
* Configuring the CI will take some significant amount of time, but if CI is our goal, we can split the process into a couple of steps to achieve that, we can start with publishing the generated definitions and keep things in sync manually as you said and later configure a CI.
* If rmf_core and traffic_editor messages are not updated very frequently I think we can update the project manually for the moment.


Just out curiosity after I install the project, with the new version of `rmf_core` and `traffic_editor`, will the following code generate the updated definitions?

``` bash
cd colcon_ws/src
git clone --depth 1 https://github.com/osrf/rmf_core.git
git clone --depth 1 https://github.com/osrf/traffic_editor
git clone https://github.com/osrf/romi-js-core-interfaces

cd colcon_ws
colcon build
npm install
```

**Comment by koonpeng** [comment]
Sorry for my unclear proposal. The first proposal is to generate the message definitions in a post-install step as the end-user do a `npm install`. To do this would require ros2 idl parsers, python, typescript among other dependencies available on the end-user's setup.

The 2nd proposal, which is what is currently happening now is to generate the definitions before hand and publish them in the npm package. With this the end user don't need to have the dependencies mentioned above, but it presents this issue where the original ros2 lift message definitions are changed while the pre-generated typescript definitions published to npm is still using the old versions.

In the ideal scenario we can have a CI pipeline that automatically publishes new versions to npm as the original ros2 definitions is changed but getting this up looks like a significant amount of work and would probably not happen soon.

So the proposal would be a question of is it worth it to introduce a bunch of dev dependencies to the end user to make sure that this issue would not happen again, or do we continue publishing the new definitions manually until we have a CI solution.

---

> Just out curiosity after I install the project, with the new version of rmf_core and traffic_editor, will the following code generate the updated definitions?

Yes, this should generate the updated definitions but you have to point package.json to use the local installation of `romi-js-core-interfaces` instead of the one from npm.

**Comment by baviera08** [comment]
Thanks for the explanation, it seems to me that it would be better to publish the generated definitions and keep them versioned in the repository. As you said, we could do it manually at the beginning and later with the help of a CI.

**Comment by koonpeng** [comment]
Thanks, I will go with the current release model for now.
